services:
  postgres:
    image: postgis/postgis:16-3.4-alpine
    container_name: postgres-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rentala
    networks:
      - backend
    volumes:
      - postgres_data:/var/lib/postgresql/data

  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    container_name: api-server
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - backend
      - frontend
    env_file:
      - ./server/.env
    volumes:
      - /app/uploads
      - /app/prisma/migrations
    develop:
      watch:
        - action: sync
          path: ./server
          target: /app
          initial_sync: true
          ignore:
            - node_modules/
        - action: rebuild
          path: ./server/package.json

    depends_on:
      - postgres

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    container_name: web-client
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - frontend
    env_file:
      - ./client/.env
    develop:
      watch:
        - action: sync
          path: ./client
          target: /app
          initial_sync: true
          ignore:
            - node_modules/
        - action: rebuild
          path: ./client/package.json

    depends_on:
      - server

volumes:
  postgres_data:

networks:
  backend:
  frontend:
